apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: mongodb
    spec: 
      containers:
        - name: mongodb
          image: mongodb:7.0.5
          env:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
            ME_CONFIG_MONGODB_ADMINPASSWORD: Jokenpo1a1
          ports:
            - containerPort: 27017
              name: mongodb    
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /var/lib/mongodb    
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script